### ISSUE TITLE
You are a hero.

### ISSUE THREAD

**Issue by rafauke** [llemaitre19/jtsx#10]
I just wanted to let you know that you are my JSX/TSX hero. This is the most feature-rich, working and predictable js mode that I have used. I've been looking for something like this for +2 years. Incredible. Tears of joy.

<3

**Comment by llemaitre19** [comment]
Thanks ! Very glad to hear this package can help some JSX/TSX programmers like you.

A part of the credit nevertheless goes to the Emacs core developers that have written the new tree-sitter modes (`js-ts-mode` and `tsx-ts-mode`) as this package is implemented on the top of them.

**Comment by rafauke** [comment]
Sure, that's true. But they don't work out of the box and don't have the extra bells & whistles. Anyway, I just wanted to express my appreciation and happiness :) Thanks again.
