### ISSUE TITLE
Feature request: Option for automatically renaming paired tag

### ISSUE THREAD

**Issue by noah-evans** [llemaitre19/jtsx#3]
I love this package, it fixes pretty much all of the pain points I had working with react in emacs! Thanks for your work.

The one thing that would be nice would be an option that automatically keeps the paired tag in sync when you edit a tag, so you can just edit without having to call 'jtsx-rename-jsx-element. 

Like this in vscode: https://code.visualstudio.com/updates/v1_79#_linked-editing-for-jsx-tags

**Comment by llemaitre19** [comment]
Thanks for your kind feedback on this package and your feature request.

I totally agree with you, it would be great to automatically rename corresponding tag. It would be more straightforward than calling `jtsx-rename-jsx-element` and would allow to benefit from completion features.

I am going to try to implement it as soon as I have some free time.

**Comment by noah-evans** [comment]
It works perfectly for editing existing tags, and it seems to work fine with corfu.

When you start typing a new tag sometimes it mistakes an existing closing tag for the tag that you're currently typing and edits that.

With point where the `|` is when you type `<p` it edits the closing tag for the div

```
<div>
  |
  <div></div>
</div>
```

```
<div>
  <p|
  <div></p>
</div>
```

If you start typing with point here instead there is no problem, it seems to be about whether point is on whitespace or not.

```
<div>
  |<div></div>
</div>
```

```
<div>
  <p|<div></div>
</div>
```

**Comment by llemaitre19** [comment]
Thank you for your tests, the last commits in the `development` branch should fix the issue.

They also add a guard to ensure that automatic sync of tags is only performed when the buffer has been just modified.

Do not hesitate to add another comment if you find a new bug.

**Comment by llemaitre19** [comment]
The feature is now in `master` branch and available in Melpa. I close the issue.
